apiVersion: v1
kind: ConfigMap
metadata:
  name: tagd-cm
  namespace: shenma
data:
  env.yaml: |
    env: local
    db:
      type: sqlite3
      databaseName: tagd
      host: ${{__env_profile.database.host}}
      port: ${{__env_profile.database.port}}
      password: ${{__env_profile.database.password}}
      user: ${{__env_profile.database.user}}
    server:
      listenAddr: ":8081"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tagd
  namespace: shenma
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tagd
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tagd
    spec:
      containers:
      - image: ${{SHENMA_DOCKER_REPO}}/tagd:${{IMAGE_TIMESTAMP}}
        imagePullPolicy: Always
        name: tagd
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 2
            memory: 2Gi
          requests:
            cpu: 1
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - mountPath: /env.yaml
            name: config-volume
            subPath: env.yaml
      volumes:
        - configMap:
            defaultMode: 420
            name: tagd-cm
          name: config-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: tagd
      serviceAccountName: tagd
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  namespace: shenma
  name: tagd
  labels:
    app: tagd
spec:
  # pod的标签选择器
  type: NodePort
  selector:
    app: tagd
  # 暴露的端口列表
  ports:
    # HTTP服务端口
    - name: http
      port: 80
      nodePort: 31224
      targetPort: 8080
      protocol: TCP

